### ISSUE TITLE
HSL/HSLUV not giving the right color

### ISSUE THREAD

**Issue by cloudUser98** [rktjmp/lush.nvim#154]
### Steps to reproduce:
1. Run the tutorial with :LushRunTutorial and :Lushify
2. Define a local variable with the value hsl(195,8,20)
3. Lushify outputs the color #303030

---

**Example:**
![image](https://github.com/user-attachments/assets/61380eae-260b-47de-a7bc-77971d2d68f3)

**Expected color:**
![image](https://github.com/user-attachments/assets/c15af5a5-0187-4c8c-9a7a-7aba22a62333)

**Actual color:**
![image](https://github.com/user-attachments/assets/8858dfbe-50b9-4c49-9a1d-f409f7139d74)

**Comment by rktjmp** [comment]
Its an effect of moving between the rgb and hsl(uv) colorspaces, where one is integer and the other floats. See https://github.com/rktjmp/lush.nvim/issues/59 https://github.com/rktjmp/lush.nvim/issues/68 https://github.com/rktjmp/lush.nvim/issues/74

**Comment by rmunn** [comment]
It would be nice to offer an [Oklab](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklab) color function, as Oklab does much better than HSL/HSV at maintaining the perceived hue when changing lightness. See https://bottosson.github.io/posts/oklab/#blending-colors for example, where CIELAB and HSV look purple in the middle of the gradiant.

Actually, that might not be what's going on here, so maybe I'll suggest an `oklab` function in a separate issue. But since discovering how much better the CSS `oklab` and `oklch` functions are at maintaining perceived color than `hsl`, I've come to really prefer them, and would like to see Lush have them available as well.

**Comment by rktjmp** [comment]
I think previously I couldn't find a good oklab/oklch lua library, but it was a year or more ago that it was last floated. Feel free to open another issue to discuss or suggest libraries.

**Comment by rmunn** [comment]
Found a few possibilities and mentioned them in #155. None of them are exactly a perfect solution, but a couple of them look like they might get you 80-90% of the way there.

**Comment by cloudUser98** [comment]
> Its an effect of moving between the rgb and hsl(uv) colorspaces, where one is integer and the other floats. See #59 #68 #74

I see, thanks for the response.
