### ISSUE TITLE
TreeSitter group names

### ISSUE THREAD

**Issue by Davincible** [rktjmp/lush.nvim#48]
I'm creating a treesitter theme, but I am having some issues with some group names. Currently testing with Go. For example, the TS groups `var_declaration, const_declaration, function_declaration, select_statement` now all fall under the group `TSKeyword`, meant for 'other' keywords, including the function declaration, which I would expect under the `TSKeywordFunction` group. 

Is it possible to create seperate groups for these?

**Comment by rktjmp** [comment]
Lush should just make whatever highlight groups you tell it to, it's up to TreeSitter, etc to apply those groups.

```lua
return lush(function()
  return {
    MyCustomGroup { fg = red }, -- custom group
    LightspeedLabel { fg = green }, -- plugin group
    TSKeywordFunction { ... },
    -- etc etc
  }
end)
```

So I think you're problem might be with the Go TreeSitter plugin not applying it's groups with enough specificity? I haven't used TS since it became mainlined though so I am only guessing.

**Comment by Davincible** [comment]
You're right. After some more digging I found out it's indeed not related to this plugin. Thanks for the pointers
