### ISSUE TITLE
Clearing default `gui=` settings.

### ISSUE THREAD

**Issue by ndreas** [rktjmp/lush.nvim#91]
With the recent changes on how the `gui=` parameter is handled, it is no longer cleared if left empty. In addition, there is no way to set `gui=NONE`.

Neovim defines a number of default `gui=` settings, for example for `hi TabLine`, and I have had to add `gui = "nocombine"` to the rules that I want to clear.

**Comment by rktjmp** [comment]
Are you able to provide a small example of how you're doing things?

Are you mixing `gui=` and `bold=true` etc? That's not recommended but if you are we can discuss ergonomic improvements perhaps.

If I define my group `TabLine { fg = red }`, the underline is removed as expected, if I inherit from it I can set `gui=""` or `gui="NONE"` to clear any that I do intentionally set. If I never define `TabLine` I can't inherit from it so that seems like a non-factor. 

Perhaps there are groups that naturally link to tabline, or I guess text *inside* a tabline?

Having trouble reproducing or understanding the issue.

**Comment by ndreas** [comment]
Files are here: https://gitlab.com/ndreas/vim-config/-/tree/main/lua/ndreas-theme
I don't use Lush dynamically, but rather build my theme into `colors/`.

**Comment by ndreas** [comment]
Yep it works great!

**Comment by rktjmp** [comment]
Fixed in  6923ccef17c5276bc5d3cca907082e19ee165d55

Thanks for reporting the issue!
